FROM --platform=$BUILDPLATFORM golang:1.25-trixie AS builder

ARG TARGETOS
ARG TARGETARCH

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY --link . .

RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -o orchestrator main.go

FROM alpine:latest AS runner

COPY --from=builder /app/orchestrator /usr/local/bin/orchestrator

CMD ["orchestrator"]