apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-orchestrator
  labels:
    app: pipeline-orchestrator
subjects:
  - kind: ServiceAccount
    name: pipeline-orchestrator
roleRef:
  kind: Role
  name: pipeline-orchestrator
  apiGroup: rbac.authorization.k8s.io